<a href="https://colab.research.google.com/github/VishnuPy/MyPython/blob/master/NLP_LDA_and_NMF_Topic_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive
%ls

Found GPU at: /device:GPU:0
Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive
/gdrive
'My Drive'/


In [2]:
import tensorflow as tf
import timeit

# See https://www.tensorflow.org/tutorials/using_gpu#allowing_gpu_memory_growth
config = tf.ConfigProto()
config.gpu_options.allow_growth = True

with tf.device('/cpu:0'):
  random_image_cpu = tf.random_normal((100, 100, 100, 3))
  net_cpu = tf.layers.conv2d(random_image_cpu, 32, 7)
  net_cpu = tf.reduce_sum(net_cpu)

with tf.device('/gpu:0'):
  random_image_gpu = tf.random_normal((100, 100, 100, 3))
  net_gpu = tf.layers.conv2d(random_image_gpu, 32, 7)
  net_gpu = tf.reduce_sum(net_gpu)

sess = tf.Session(config=config)

# Test execution once to detect errors early.
try:
  sess.run(tf.global_variables_initializer())
except tf.errors.InvalidArgumentError:
  print(
      '\n\nThis error most likely means that this notebook is not '
      'configured to use a GPU.  Change this in Notebook Settings via the '
      'command palette (cmd/ctrl-shift-P) or the Edit menu.\n\n')
  raise

def cpu():
  sess.run(net_cpu)
  
def gpu():
  sess.run(net_gpu)
  
# Runs the op several times.
print('Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images '
      '(batch x height x width x channel). Sum of ten runs.')
print('CPU (s):')
cpu_time = timeit.timeit('cpu()', number=10, setup="from __main__ import cpu")
print(cpu_time)
print('GPU (s):')
gpu_time = timeit.timeit('gpu()', number=10, setup="from __main__ import gpu")
print(gpu_time)
print('GPU speedup over CPU: {}x'.format(int(cpu_time/gpu_time)))

Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
Instructions for updating:
Please use `layer.__call__` method instead.
Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images (batch x height x width x channel). Sum of ten runs.
CPU (s):
2.8438905259999956
GPU (s):
5.861171678000005
GPU speedup over CPU: 0x


In [3]:
import pandas as pd
import numpy as np


reviews_datasets = pd.read_csv("/gdrive/My Drive/MyLearning/MLDLAIPython/Data/Reviews.csv")
reviews_datasets = reviews_datasets.head(20000)
reviews_datasets.dropna()

Id  ...                                               Text
0          1  ...  I have bought several of the Vitality canned d...
1          2  ...  Product arrived labeled as Jumbo Salted Peanut...
2          3  ...  This is a confection that has been around a fe...
3          4  ...  If you are looking for the secret ingredient i...
4          5  ...  Great taffy at a great price.  There was a wid...
...      ...  ...                                                ...
19995  19996  ...  Deep River Salt & Vinegar chips are thick and ...
19996  19997  ...  I was very skeptical about buying a brand of c...
19997  19998  ...  Before you turn to other name brands out there...
19998  19999  ...  I was expecting some "serious flavor" as it wa...
19999  20000  ...  I purchased the Salt and Vinegar chips and hav...

[20000 rows x 10 columns]

In [4]:
reviews_datasets.head()

Id  ...                                               Text
0   1  ...  I have bought several of the Vitality canned d...
1   2  ...  Product arrived labeled as Jumbo Salted Peanut...
2   3  ...  This is a confection that has been around a fe...
3   4  ...  If you are looking for the secret ingredient i...
4   5  ...  Great taffy at a great price.  There was a wid...

[5 rows x 10 columns]

In [5]:
reviews_datasets['Text'][350]

'These chocolate covered espresso beans are wonderful!  The chocolate is very dark and rich and the "bean" inside is a very delightful blend of flavors with just enough caffine to really give it a zing.'

<font color=green size=4>
Create V0cabulary of all the words in the Dataset

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(max_df=0.80, min_df=2, stop_words='english')
doc_term_matrix = count_vect.fit_transform(reviews_datasets['Text'].values.astype('U'))

In [7]:
doc_term_matrix

<20000x14546 sparse matrix of type '<class 'numpy.int64'>'
	with 594703 stored elements in Compressed Sparse Row format>

<font color=brown size=3>
In the above output of doc term matrix: Vocabulary has 14546 words across 20000 rows. Meaning 14546 features (vectors) <br>
Now, we will use LDA to create topics along with the probability distribution for each word in our vocabulary for each topic.

In [8]:
from sklearn.decomposition import LatentDirichletAllocation

LDA = LatentDirichletAllocation(n_components=10, random_state=42) #n_components is limiting to 5 categories
LDA.fit(doc_term_matrix)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=10, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

<font color=green size=3>
Randomly check the words in the vocabulary by passing the ID to the doc matrix

In [9]:
import random

for i in range(10):
    random_id = random.randint(0, len(count_vect.get_feature_names()))
    print (count_vect.get_feature_names()[random_id])

eatable
juice
labor
outrageous
inform
consistancy
sunset
smash
discharge
evans


In [10]:
first_topic = LDA.components_[0] #LDA.components_ contains the probability of each word 
print (first_topic) #first_topic contains the probability of 14564 words of Topic1

[0.10001071 0.10001649 0.1        ... 0.10000065 0.10000195 0.10000258]


In [11]:
LDA.components_

array([[0.10001071, 0.10001649, 0.1       , ..., 0.10000065, 0.10000195,
        0.10000258],
       [0.10001   , 4.6345964 , 0.10000488, ..., 1.17836732, 0.1       ,
        0.1000002 ],
       [0.10001262, 3.48449645, 0.10000226, ..., 0.1       , 0.10000649,
        0.10001156],
       ...,
       [0.13485358, 1.45242086, 1.15800388, ..., 0.1000137 , 0.10000077,
        0.10000172],
       [5.50340645, 8.35389808, 4.04194284, ..., 0.10001085, 0.10000356,
        0.10000318],
       [2.34582704, 0.10001217, 0.1       , ..., 0.10008356, 0.10000034,
        0.10000006]])

In [0]:
top_topic_words = first_topic.argsort()[-10:]

In [13]:
top_topic_words # gives out the index of the top 10 words in topic 1. use these indexs to get the words

array([12888,  7644,  5912, 10221,  5771,  5902, 12937,  7498,  5304,
       12921])

In [14]:
for i in top_topic_words:
    print(count_vect.get_feature_names()[i])

taste
loose
grey
quality
good
green
teas
like
food
tea


<font color=blue size=3>
Above 10 words in the topic might be related to Tea <br>
<font color=brown size=4>
Lets print out top 10 words for all 5 topics

In [15]:
for i, topic in enumerate(LDA.components_):
    print(f'Top 10 words for topic #{i}:')
    print ([count_vect.get_feature_names()[i] for i in topic.argsort()[-10:]])
    print ('\n')


Top 10 words for topic #0:
['taste', 'loose', 'grey', 'quality', 'good', 'green', 'teas', 'like', 'food', 'tea']


Top 10 words for topic #1:
['salt', 'love', 'just', 'great', 'flavor', 'good', 'taste', 'chips', 'like', 'chocolate']


Top 10 words for topic #2:
['time', 'plant', 'small', 'product', 'great', 'use', 'just', 'cats', 'cat', 'br']


Top 10 words for topic #3:
['old', 'br', 'treat', 'eat', 'loves', 'like', 'dogs', 'treats', 'food', 'dog']


Top 10 words for topic #4:
['time', 'ordered', 'box', 'great', 'buy', 'shipping', 'order', 'price', 'product', 'amazon']


Top 10 words for topic #5:
['just', 'great', 'taste', 'good', 'flavor', 'cups', 'like', 'cup', 'br', 'coffee']


Top 10 words for topic #6:
['don', 'price', 'water', 'love', 'just', 'really', 'good', 'like', 'taste', 'great']


Top 10 words for topic #7:
['soda', 'sugar', 'just', 'good', 'juice', 'drink', 'taste', 'flavor', 'like', 'br']


Top 10 words for topic #8:
['free', 'taste', 'good', 'protein', 'just', 'ingred

<font color=green size=3>
The above seem like 1st topic is Tea; 2nd is Chocolate chips; 3rd topic is Orange juice; 4th is about bad food habits; 5th topic is about Amazon Shopping <br>
<font color=brown size=3>
Now will have Topic column added to each of the reviews/documents and have probability of the document relevant to the topic, then We can populate the topic that has highest probability (using Argmax).

In [16]:
topic_values = LDA.transform(doc_term_matrix)
topic_values.shape

(20000, 10)

In [0]:
reviews_datasets['Topic'] = topic_values.argmax(axis=1)

In [18]:
reviews_datasets.head()

Id   ProductId  ...                                               Text Topic
0   1  B001E4KFG0  ...  I have bought several of the Vitality canned d...     3
1   2  B00813GRG4  ...  Product arrived labeled as Jumbo Salted Peanut...     4
2   3  B000LQOCH0  ...  This is a confection that has been around a fe...     1
3   4  B000UA0QIQ  ...  If you are looking for the secret ingredient i...     7
4   5  B006K2ZZ7K  ...  Great taffy at a great price.  There was a wid...     6

[5 rows x 11 columns]

<font color=blue size=6>
Non Negative Matrix Factorization (NMF): <br>
<font color=blue size=3>
Is a Supervised Learning Technique to perform Clusteringa as well as Dimensionality Reduction.

In [26]:
reviews_datasets = pd.read_csv("/gdrive/My Drive/MyLearning/MLDLAIPython/Data/Reviews.csv")
reviews_datasets = reviews_datasets.head(20000)
reviews_datasets.dropna()

Id  ...                                               Text
0          1  ...  I have bought several of the Vitality canned d...
1          2  ...  Product arrived labeled as Jumbo Salted Peanut...
2          3  ...  This is a confection that has been around a fe...
3          4  ...  If you are looking for the secret ingredient i...
4          5  ...  Great taffy at a great price.  There was a wid...
...      ...  ...                                                ...
19995  19996  ...  Deep River Salt & Vinegar chips are thick and ...
19996  19997  ...  I was very skeptical about buying a brand of c...
19997  19998  ...  Before you turn to other name brands out there...
19998  19999  ...  I was expecting some "serious flavor" as it wa...
19999  20000  ...  I purchased the Salt and Vinegar chips and hav...

[20000 rows x 10 columns]

In [27]:
reviews_datasets.shape

(20000, 10)

In [28]:
reviews_datasets['Text'][350]

'These chocolate covered espresso beans are wonderful!  The chocolate is very dark and rich and the "bean" inside is a very delightful blend of flavors with just enough caffine to really give it a zing.'

In [29]:
reviews_datasets.head()

Id  ...                                               Text
0   1  ...  I have bought several of the Vitality canned d...
1   2  ...  Product arrived labeled as Jumbo Salted Peanut...
2   3  ...  This is a confection that has been around a fe...
3   4  ...  If you are looking for the secret ingredient i...
4   5  ...  Great taffy at a great price.  There was a wid...

[5 rows x 10 columns]

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(min_df=2, max_df=0.80, stop_words='english')
doc_term_matrix = tfidf_vect.fit_transform(reviews_datasets['Text'].values.astype('U'))

In [31]:
from sklearn.decomposition import NMF

nmf = NMF(n_components=5, random_state=42)
nmf.fit(doc_term_matrix)

NMF(alpha=0.0, beta_loss='frobenius', init=None, l1_ratio=0.0, max_iter=200,
    n_components=5, random_state=42, shuffle=False, solver='cd', tol=0.0001,
    verbose=0)

In [37]:
import random

for i in range(10):
    random_id = random.randint(0, len(tfidf_vect.get_feature_names()))
    print(tfidf_vect.get_feature_names()[random_id])

grabbing
winter
everyday
age
gastric
litter
screws
cumin
effectively
kopi


In [0]:
first_topic = nmf.components_[0]
top_topic_words = first_topic.argsort()[-10:]

In [41]:
for i in top_topic_words:
    print(tfidf_vect.get_feature_names()[i])

really
chocolate
love
flavor
just
product
taste
great
good
like


In [44]:
for i, topic in enumerate(nmf.components_):
    print(f'Top 10 words for topic #{i}:')
    print([tfidf_vect.get_feature_names()[i] for i in topic.argsort()[-10:]])
    print('\n')

Top 10 words for topic #0:
['really', 'chocolate', 'love', 'flavor', 'just', 'product', 'taste', 'great', 'good', 'like']


Top 10 words for topic #1:
['like', 'keurig', 'roast', 'flavor', 'blend', 'bold', 'strong', 'cups', 'cup', 'coffee']


Top 10 words for topic #2:
['com', 'amazon', 'orange', 'switch', 'water', 'drink', 'soda', 'sugar', 'juice', 'br']


Top 10 words for topic #3:
['bags', 'flavor', 'drink', 'iced', 'earl', 'loose', 'grey', 'teas', 'green', 'tea']


Top 10 words for topic #4:
['old', 'love', 'cat', 'eat', 'treat', 'loves', 'dogs', 'food', 'treats', 'dog']




In [45]:
topic_values = nmf.transform(doc_term_matrix)
reviews_datasets['Topic'] = topic_values.argmax(axis=1)
reviews_datasets.head()

Id   ProductId  ...                                               Text Topic
0   1  B001E4KFG0  ...  I have bought several of the Vitality canned d...     4
1   2  B00813GRG4  ...  Product arrived labeled as Jumbo Salted Peanut...     0
2   3  B000LQOCH0  ...  This is a confection that has been around a fe...     4
3   4  B000UA0QIQ  ...  If you are looking for the secret ingredient i...     0
4   5  B006K2ZZ7K  ...  Great taffy at a great price.  There was a wid...     0

[5 rows x 11 columns]